"use client";
/* eslint-disable @typescript-eslint/no-unsafe-assignment */
import Navbar from "@/components/Layout/NavbarLogin";
import Head from "next/head";
import Router from "next/router";
import React from "react";

interface volunteer {
  id: string;
  name: string;
  email: string;
  role: string;
  gender: string;
  phone: string;
  address: string;
  category: Array<string>;
  ngo: string;
  createdAt: string;
  updatedAt: string;
}

function Volunteers() {
  // let data: string | null = "";
  // if (typeof window !== "undefined") {
  //   data = localStorage.getItem("volunteers");
  // }
  // // if (!data) {
  // //   void Router.push("/home");
  // // }
  // const volunteers: Array<volunteer> = JSON.parse(data as string);
  return (
    <>
      <Head>
        <title>CareBridge | Volunteers</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className="mx-[10%]">
        <p className="my-5 mb-20 text-left text-2xl font-bold lg:text-5xl">
          Available Volunteers:
        </p>
        {/* {volunteers.map((volunteer: volunteer, index) => ( */}
        <div
          // key={index}
          className="volunteer-box my-4 flex flex-col gap-4 rounded-xl p-5 text-lg"
        >
          <div className="flex items-center">
            <svg
              width="100"
              height="100"
              viewBox="0 0 100 100"
              fill="none"
              xmlns="http://www.w3.org/2000/svg"
            >
              <circle cx="50" cy="50" r="40" fill="#CCCCCF" />
            </svg>
            {/* <p className="ml-5">{volunteer.name}</p> */}
            <p className="ml-5">Name</p>
          </div>
          <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Provident
            sit nihil modi necessitatibus minima, non nobis dignissimos ea ex
            illum. Lorem ipsum dolor sit amet, consectetur adipisicing elit.
            Similique, ex!
          </p>
          <button
            className="w-full rounded-md bg-[#56B280] px-5 py-3 text-white lg:ml-auto lg:w-fit"
            onClick={() => {
              void Router.push("/volunteerAssigned");
            }}
          >
            Confirm
          </button>
        </div>
        {/* ))} */}
      </main>
    </>
  );
}

export default Volunteers;
