import Navbar from "@/components/Layout/NavbarLogin";
import Head from "next/head";
import React from "react";

function volunteers() {
  return (
    <>
      <Head>
        <title>CareBridge | Volunteers</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className="mx-[10%]">
        <p className="my-5 mb-20 text-left text-2xl font-bold lg:text-5xl">
          Available Volunteers:
        </p>

        <div className="volunteer-box my-4 flex flex-col gap-4 text-lg rounded-xl p-5">
          <div className="flex items-center">
            <svg
              width="100"
              height="100"
              viewBox="0 0 100 100"
              fill="none"
              xmlns="http://www.w3.org/2000/svg"
            >
              <circle cx="50" cy="50" r="40" fill="#CCCCCF" />
            </svg>
            <p className="ml-5">Name</p>
          </div>
            <p>
              Vaibhav is a compassionate volunteer who selflessly gives his time
              and skills to make a positive impact. His dedication and empathy
              bring joy and support to those he serves in the community.
            </p>
            <button className="w-full rounded-md bg-[#56B280] px-5 py-3 text-white lg:w-fit lg:ml-auto">
                Confirm
            </button>
        </div>
      </main>
    </>
  );
}

export default volunteers;
