
import Reviews from "@/components/Home/Reviews";
import Hero from "@/components/Home/Hero";
import Navbar from "@/components/Layout/NavbarLogin";
import { type NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>CareBridge</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar />
        <Hero />
        <Reviews />
      </main>
    </>
  );
};

export default Home;